/* ==========================================================================
   부산 장소/맛집/액티비티 데이터
   가격은 검색 시점(2026.07) 기준이며 변동될 수 있음 — 링크에서 최신 확인 권장
   ========================================================================== */

window.PLACES = [
  {
    id: 'sky-capsule',
    category: '액티비티',
    name: '해운대 블루라인파크 스카이캡슐',
    area: '미포 ↔ 청사포',
    price: '2인승 35,000원~ (편도, 예약 필수)',
    signature: '해안선 위 캡슐열차',
    desc: '8/10 확정 코스! 성수기엔 매진 빠르니 미리 예약.',
    icon: 'capsule',
    link: 'https://www.bluelinepark.com/skyCapsuleFare.do',
  },
  {
    id: 'x-the-sky',
    category: '액티비티',
    name: '엑스더스카이 (X the SKY)',
    area: '해운대 엘시티 100층',
    price: '대인 29,000원 · 소인 26,000원 (온라인 예매 할인 많음)',
    signature: '100층 파노라마 오션뷰',
    desc: '해질녘에 올라가면 노을 + 야경 둘 다 가능.',
    icon: 'tower',
    link: 'https://www.busanxthesky.com/',
  },
  {
    id: 'songjeong-surf',
    category: '액티비티',
    name: '송정 서핑 강습',
    area: '송정해수욕장 (숙소 도보권)',
    price: '입문 1일 65,000원~ (보드·슈트 대여 포함)',
    signature: '입문 강습 2시간 + 자유서핑',
    desc: '숙소 바로 앞이라 접근성 최고, 여름 성수기 예약 권장.',
    icon: 'wave',
    link: 'https://www.surfholic.co.kr/branch/songjeong_price.php',
  },
  {
    id: 'the-bay101',
    category: '명소',
    name: '더베이101',
    area: '해운대 마린시티',
    price: '입장 무료 (매장 이용은 별도)',
    signature: '요트 정박지 야경',
    desc: '저녁 산책하면서 야경 보기 좋은 곳.',
    icon: 'city',
    link: 'https://map.naver.com/p/search/더베이101',
  },
  {
    id: 'cheongsapo',
    category: '명소',
    name: '청사포 다릿돌전망대',
    area: '청사포',
    price: '무료 (09:00~18:00, 여름 야간 연장)',
    signature: '바다 위 191m 스카이워크',
    desc: '블루라인파크 청사포역 근처, 잠깐 들르기 좋음.',
    icon: 'view',
    link: 'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=d24fc1d9-56ee-4cec-b8c5-8ba1f20101ee',
  },
  {
    id: 'yonggungsa',
    category: '명소',
    name: '해동용궁사',
    area: '기장',
    price: '무료 (주차 유료, 4:30~19:00)',
    signature: '바다 바로 앞 사찰',
    desc: '파도 소리 들으며 사진 찍기 좋은 곳.',
    icon: 'temple',
    link: 'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=2116b628-ded9-42c2-b17e-99d17b5b65e4',
  },
  {
    id: 'gamcheon',
    category: '명소',
    name: '감천문화마을',
    area: '사하구 (숙소에서 다소 거리 있음)',
    price: '입장 무료 (스탬프 지도 2,000원)',
    signature: '계단식 컬러풀 마을',
    desc: '시간 여유 될 때만, 이동 시간 감안하기.',
    icon: 'village',
    link: 'https://www.gamcheon.or.kr/',
  },
  {
    id: 'gwangalli',
    category: '명소',
    name: '광안리 해변 · 광안대교 야경',
    area: '수영구 광안리',
    price: '무료',
    signature: '초 단위로 바뀌는 광안대교 조명',
    desc: '해운대에서 차로 15분, 밤 드라이브 코스.',
    icon: 'bridge',
    link: 'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=98763dd6-119d-4e32-910e-a40652334bda',
  },
  {
    id: 'gijang-crab',
    category: '맛집',
    name: '기장 대게',
    area: '기장시장',
    price: 'kg당 65,000~85,000원대 + 상차림비 5,000원 (매장별 상이)',
    signature: '대게 찜 + 라면사리',
    desc: '시세 변동 있음, 방문 전 가격 확인 추천.',
    icon: 'crab',
    link: 'https://www.diningcode.com/profile.php?rid=ISsPwxVgxGY3',
  },
  {
    id: 'ssiat-hotteok',
    category: '맛집',
    name: '해운대시장 씨앗호떡',
    area: '해운대시장',
    price: '개당 2,000~2,500원 (치즈 추가 3,000원)',
    signature: '씨앗호떡 · 치즈호떡',
    desc: '가볍게 걸어다니면서 먹기 좋은 국룰 간식.',
    icon: 'snack',
    link: 'https://www.diningcode.com/list.dc?query=%ED%95%B4%EC%9A%B4%EB%8C%80%EC%8B%9C%EC%9E%A5+%EC%94%A8%EC%95%97%ED%98%B8%EB%96%A1',
  },
  {
    id: 'haeridangil',
    category: '카페',
    name: '해리단길 카페거리',
    area: '해운대 해리단길',
    price: '1인 15,000~20,000원대',
    signature: '브런치 + 감성 카페',
    desc: '느긋한 오전/오후 코스로 딱.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/해운대 해리단길',
  },
  {
    id: 'millak-hwe',
    category: '맛집',
    name: '민락수변공원 활어회',
    area: '수영구 민락동',
    price: '2인 6~8만원대 (시세 변동)',
    signature: '활어회 + 매운탕',
    desc: '광안대교 보면서 회 먹는 코스, 야경까지 한번에.',
    icon: 'fish',
    link: 'https://map.naver.com/p/search/민락수변공원 활어회센터',
  },
  {
    id: 'lotte-world-adventure',
    category: '액티비티',
    name: '롯데월드 어드벤처 부산',
    area: '기장 오시리아관광단지',
    price: '1일 종합이용권 온라인 성인 약 43,900원~ (현장가보다 할인)',
    signature: '자이로드롭 · 자이로스윙 등 놀이기구',
    desc: '숙소에서 좀 떨어져 있으니(차량 이동) 하루 코스로 잡기.',
    icon: 'coaster',
    link: 'https://adventurebusan.lotteworld.com/price/price',
  },
  {
    id: 'sealife-aquarium',
    category: '액티비티',
    name: '씨라이프 부산아쿠아리움',
    area: '해운대 (블루라인파크 인근)',
    price: '대인 30,000원 · 소인 25,000원',
    signature: '수족관 + 해양생물 체험',
    desc: '더위 피해 실내로 도는 코스로 넣기 좋음.',
    icon: 'fish',
    link: 'https://www.visitsealife.com/busan/en/tickets-passes/',
  },
  {
    id: 'songdo-cable-car',
    category: '액티비티',
    name: '송도해상케이블카',
    area: '서구 송도',
    price: '크리스탈크루즈 왕복 대인 22,000원 · 편도 17,000원',
    signature: '투명 바닥 크리스탈 캐빈',
    desc: '숙소에서 거리 있는 원도심 방향, 시간 여유 될 때.',
    icon: 'cablecar',
    link: 'https://www.busanaircruise.co.kr/',
  },
  {
    id: 'taejongdae-danubi',
    category: '액티비티',
    name: '태종대 다누비열차',
    area: '영도 태종대',
    price: '대인 4,000원 · 소인 2,000원',
    signature: '태종대 순환 관광열차',
    desc: '영도 절벽 드라이브 코스, 걷기 힘들면 열차로.',
    icon: 'train',
    link: 'http://taejongdae.bisco.or.kr/facil/facil01/facil01_1/',
  },
  {
    id: 'spaland',
    category: '액티비티',
    name: '센텀시티 스파랜드',
    area: '해운대구 센텀시티',
    price: '성인 23,000원 (4시간 기준)',
    signature: '찜질방 + 테마 사우나',
    desc: '비 오는 날이나 마지막 날 몸 풀기 코스로 좋음.',
    icon: 'spa',
    link: 'https://www.shinsegae.com/store/entertainment/centum-spaland.do?storeCd=SC00008',
  },
  {
    id: 'oryukdo-skywalk',
    category: '명소',
    name: '오륙도 스카이워크',
    area: '남구',
    price: '무료',
    signature: '35m 절벽 위 유리 스카이워크',
    desc: '숙소에서 거리 있지만 사진 명소로 유명.',
    icon: 'view',
    link: 'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=6cb1642d-b578-462f-82c6-b1c1ef468af7',
  },
  {
    id: 'igidae',
    category: '명소',
    name: '이기대 해안산책로',
    area: '남구',
    price: '무료',
    signature: '해안 절벽 트레킹 코스',
    desc: '걷기 좋아하면 추천, 왕복 2~3시간 코스.',
    icon: 'trail',
    link: 'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=bbec35d0-16f1-4350-9911-e18716252102',
  },
  {
    id: 'busan-tower',
    category: '명소',
    name: '부산타워 · 용두산공원',
    area: '중구 남포동',
    price: '공원 무료 · 타워 전망대 약 12,000원 (변동 가능)',
    signature: '원도심 전망대',
    desc: '자갈치·국제시장이랑 묶어서 원도심 코스로.',
    icon: 'tower',
    link: 'https://www.visitbusan.net/index.do?menuCd=DOM_000000201001001000&uc_seq=368&lang_cd=ko',
  },
  {
    id: 'dwaeji-gukbap',
    category: '맛집',
    name: '부산 돼지국밥',
    area: '부산 전역 (서면·남포 등)',
    price: '한 그릇 7,000~10,000원대',
    signature: '돼지국밥 + 다대기',
    desc: '부산 왔으면 한 끼는 꼭. 매장마다 편차 크니 취향껏.',
    icon: 'bowl',
    link: 'https://www.diningcode.com/list.dc?query=%EB%B6%80%EC%82%B0+%EB%8F%BC%EC%A7%80%EA%B5%AD%EB%B0%A5',
  },
  {
    id: 'milmyeon',
    category: '맛집',
    name: '부산 밀면',
    area: '부산 전역',
    price: '비빔/물밀면 7,000~8,000원대',
    signature: '비빔밀면 + 만두',
    desc: '여름에 시원하게 먹기 좋은 부산 대표 음식.',
    icon: 'bowl',
    link: 'https://www.diningcode.com/list.dc?query=%EB%B6%80%EC%82%B0+%EB%B0%80%EB%A9%B4',
  },
  {
    id: 'jeonpo-cafe',
    category: '카페',
    name: '전포카페거리',
    area: '부산진구 전포동',
    price: '1인 6,000~15,000원대',
    signature: '개성 있는 카페 · 디저트',
    desc: '숙소에서 거리 있는 편, 카페 투어 좋아하면 추천.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/전포카페거리',
  },
  {
    id: 'gukje-market',
    category: '맛집',
    name: '국제시장 · 부평깡통시장',
    area: '중구 원도심',
    price: '먹거리 1인 5,000~15,000원대',
    signature: '유부주머니 · 비빔당면 · 닭강정',
    desc: '원도심 코스로 자갈치·부산타워랑 묶기 좋음.',
    icon: 'market',
    link: 'https://map.naver.com/p/search/국제시장',
  },
  {
    id: 'jagalchi-hwe',
    category: '맛집',
    name: '자갈치시장 회',
    area: '중구 자갈치',
    price: '2인 시세 (변동, 6~10만원대 참고)',
    signature: '활어회 · 건어물',
    desc: '부산 대표 수산시장, 원도심 코스에 묶기 좋음.',
    icon: 'fish',
    link: 'https://map.naver.com/p/search/자갈치시장',
  },
  {
    id: 'huinnyeoul',
    category: '명소',
    name: '흰여울문화마을',
    area: '영도',
    price: '무료 (카페 이용 별도)',
    signature: '바다 절벽 위 골목 마을',
    desc: '사진 스팟 많음, 카페거리도 같이 있음.',
    icon: 'village',
    link: 'https://map.naver.com/p/search/흰여울문화마을',
  },
  {
    id: 'busan-sea-festival',
    category: '액티비티',
    name: '부산바다축제 (다대포)',
    area: '사하구 다대포해수욕장',
    price: '무료 (일부 부스·체험 유료)',
    signature: '불꽃쇼 + 공연 + 해변 포차',
    desc: '2026년 8/7~13 개최라 마침 여행 기간(8/9~11)이랑 겹침! 숙소에서는 거리 있음.',
    icon: 'festival',
    link: 'https://festivalbusan.com/seafestival/',
  },
  {
    id: 'moon-toast',
    category: '카페',
    name: '문토스트 (송정 본점)',
    area: '송정해변로 16 (숙소 도보권)',
    price: '모짜렐라 치즈토스트 6,000원대',
    signature: '모짜렐라 치즈토스트',
    desc: '숙소 근처 야식/간식 코스, 화요일 휴무 체크.',
    icon: 'toast',
    link: 'https://www.diningcode.com/profile.php?rid=hb3lKZI7MySr',
  },
  {
    id: 'suwolgyeonghwa',
    category: '카페',
    name: '수월경화',
    area: '송정중앙로6번길 188 4층',
    price: '아메리카노 5,500원 · 전통차 7,500원대',
    signature: '오션뷰 전통차 + 다식',
    desc: '송정 해변 정면 오션뷰 찻집, 숙소에서 가까움.',
    icon: 'cafe',
    link: 'https://www.diningcode.com/profile.php?rid=WBsqhuExIxDJ',
  },
  {
    id: 'cafe-ban',
    category: '카페',
    name: '카페 반',
    area: '해운대 달맞이길',
    price: '음료 1인 7,000~9,000원대 (매장 확인 필요)',
    signature: '오션뷰 창가석 + 디저트',
    desc: '달맞이길 언덕 오션뷰 카페, 노을 시간대 추천.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/카페 반 해운대',
  },
  {
    id: 'rendezvous-haeundae',
    category: '카페',
    name: '랑데자뷰 해운대점',
    area: '해운대',
    price: '음료 1인 7,000~10,000원대 (매장 확인 필요)',
    signature: '해운대 대표 오션뷰 카페',
    desc: '오래된 해운대 오션뷰 카페 강자.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/랑데자뷰 해운대점',
  },
  {
    id: 'port1902',
    category: '카페',
    name: '포트 1902',
    area: '송정 (숙소 도보권)',
    price: '음료 1인 8,000~12,000원대 (매장 확인 필요)',
    signature: '야외 테라스 + 수영장 뷰',
    desc: '휴양지 느낌 나는 대형 카페, 숙소에서 가까움.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/포트1902 송정',
  },
  {
    id: 'gemstone-songjeong',
    category: '카페',
    name: '젬스톤',
    area: '송정 (숙소 도보권)',
    price: '음료 1인 7,000원대 (매장 확인 필요)',
    signature: '통유리 오션뷰',
    desc: '어느 자리에 앉아도 바다 보이는 송정 대표 카페.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/젬스톤 송정',
  },
  {
    id: 'gonggeuk-sand-coffee',
    category: '카페',
    name: '공극샌드커피',
    area: '송정',
    price: '음료 1인 6,000~8,000원대 (매장 확인 필요)',
    signature: '3층 루프톱',
    desc: '화이트톤 인테리어, 루프톱에서 송정 해변 조망.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/공극샌드커피',
  },
  {
    id: 'oldmug',
    category: '카페',
    name: '올드머그',
    area: '송정',
    price: '음료 1인 6,000~8,000원대 (매장 확인 필요)',
    signature: '빈티지 인더스트리얼 인테리어',
    desc: '평점 좋은 송정 로컬 카페.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/올드머그 송정',
  },
  {
    id: '220volt-osiria',
    category: '카페',
    name: '220볼트 오시리아',
    area: '기장 오시리아',
    price: '음료 1인 7,000~9,000원대 (매장 확인 필요)',
    signature: '대형 오션뷰 + 라이브 재즈·플리마켓',
    desc: '가구 브랜드가 운영하는 대형 카페, 행사 있는 날도 있음.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/220볼트 오시리아',
  },
  {
    id: 'off-o',
    category: '카페',
    name: '오프오',
    area: '기장',
    price: '음료 1인 7,000~9,000원대 (매장 확인 필요)',
    signature: '대형 오션뷰 카페',
    desc: '드라마 촬영지로 알려진 기장 핫플.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/오프오 기장',
  },
  {
    id: 'seantree-pension-cafe',
    category: '카페',
    name: '씨앤트리 펜션 카페',
    area: '기장',
    price: '음료 1인 7,000원대 (매장 확인 필요)',
    signature: '수영장 + 오션뷰',
    desc: '1~5층 규모, 수영장까지 있는 대형 카페.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/씨앤트리 펜션카페 기장',
  },
  {
    id: 'wave-on',
    category: '카페',
    name: '카페 웨이브온',
    area: '기장',
    price: '음료 1인 7,000원대 (매장 확인 필요)',
    signature: '루프톱 로스터리 카페',
    desc: '파도 소리 들으며 쉬기 좋은 로스터리 카페.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/웨이브온 기장',
  },
  {
    id: 'the-gama',
    category: '카페',
    name: '더가마',
    area: '기장',
    price: '전통차·화과자 1인 8,000~12,000원대 (매장 확인 필요)',
    signature: '한옥 전통찻집',
    desc: '조용하고 차분한 한옥 분위기, 화과자 세트 유명.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/더가마 기장',
  },
  {
    id: 'deborom',
    category: '카페',
    name: '데보롬',
    area: '기장',
    price: '음료 1인 7,000원대 (매장 확인 필요)',
    signature: '감성 촬영 스팟 카페',
    desc: '인생샷 스팟으로 알려진 기장 카페.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/데보롬 기장',
  },
  {
    id: 'hasamudon-coffee',
    category: '카페',
    name: '하사무돈커피 송정비치점',
    area: '송정해수욕장 (숙소 도보권)',
    price: '커피 1잔 4,000~6,000원대 (매장 확인 필요)',
    signature: '가성비 오션뷰 커피',
    desc: '숙소 근처, 부담 없는 가격의 오션뷰 커피.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/하사무돈커피 송정비치점',
  },
  {
    id: 'coralani',
    category: '카페',
    name: '코랄라니',
    area: '송정',
    price: '음료 1인 7,000원대 (매장 확인 필요)',
    signature: '감성 인테리어 카페',
    desc: '평점 좋은 송정 카페 중 하나.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/코랄라니 송정',
  },
  {
    id: 'seonchang-hwe',
    category: '맛집',
    name: '선창횟집',
    area: '해운대',
    price: '2인 시세 (변동, 매장 확인 필요)',
    signature: '활어회',
    desc: '해운대 현지인 추천 횟집.',
    icon: 'fish',
    link: 'https://map.naver.com/p/search/선창횟집 해운대',
  },
  {
    id: 'haeundae-obok-gukbap',
    category: '맛집',
    name: '해운대 오복돼지국밥',
    area: '해운대',
    price: '한 그릇 9,000원대 (매장 확인 필요)',
    signature: '돼지국밥',
    desc: '해운대 현지인 추천 돼지국밥집.',
    icon: 'bowl',
    link: 'https://map.naver.com/p/search/해운대 오복돼지국밥',
  },
  {
    id: 'schedule-haeundae',
    category: '맛집',
    name: '스케줄 해운대',
    area: '해운대',
    price: '1인 15,000~25,000원대 (매장 확인 필요)',
    signature: '양식 · 브런치',
    desc: '현지인 추천 리스트에 자주 오르는 곳.',
    icon: 'cafe',
    link: 'https://map.naver.com/p/search/스케줄 해운대',
  },
  {
    id: 'geumsu-bokguk',
    category: '맛집',
    name: '금수복국 해운대본점',
    area: '해운대',
    price: '뚝배기 복국 13,000원대~ (매장 확인 필요)',
    signature: '뚝배기 복국',
    desc: '46년 전통 복국 전문점.',
    icon: 'bowl',
    link: 'https://map.naver.com/p/search/금수복국 해운대본점',
  },
  {
    id: 'gaya-milmyeon-haeundae',
    category: '맛집',
    name: '해운대 가야밀면',
    area: '해운대',
    price: '밀면 8,000원대 (매장 확인 필요)',
    signature: '밀면',
    desc: '22년 전통, 여름철 현지인 단골집.',
    icon: 'bowl',
    link: 'https://map.naver.com/p/search/해운대 가야밀면',
  },
  {
    id: 'mipojip',
    category: '맛집',
    name: '미포집 해운대본점',
    area: '미포',
    price: '해물장 솥밥 1인 20,000원대~ (매장 확인 필요)',
    signature: '모듬해물장 솥밥',
    desc: '오픈 3개월 만에 하루 1000명 방문한 화제의 맛집.',
    icon: 'bowl',
    link: 'https://map.naver.com/p/search/미포집 해운대본점',
  },
  {
    id: 'haeundae-dalin-makchang',
    category: '맛집',
    name: '해운대 달인막창',
    area: '해운대',
    price: '1인분 15,000~20,000원대 (매장 확인 필요)',
    signature: '한우 곱창 · 막창',
    desc: '단체·대가족 방문 좋은 곱창집.',
    icon: 'flame',
    link: 'https://map.naver.com/p/search/해운대 달인막창',
  },
  {
    id: 'lee-halmae-hwe',
    category: '맛집',
    name: '이씨할매횟집',
    area: '미포',
    price: '2인 시세 (변동, 매장 확인 필요)',
    signature: '자연산 잡어회',
    desc: '미포 방파제 앞, 항구 전망 좋은 활어회집.',
    icon: 'fish',
    link: 'https://map.naver.com/p/search/이씨할매횟집 미포',
  },
  {
    id: 'nakbuljip-songjeong',
    category: '맛집',
    name: '낙불집 송정본점',
    area: '송정 (숙소 도보권)',
    price: '1인분 15,000원대 (매장 확인 필요)',
    signature: '낙지볶음(낙불볶음)',
    desc: '화끈한 불맛의 낙지볶음, 숙소 근처.',
    icon: 'flame',
    link: 'https://map.naver.com/p/search/낙불집 송정본점',
  },
  {
    id: 'holy-lounge-songjeong',
    category: '맛집',
    name: '홀리라운지 송정본점',
    area: '송정 (숙소 도보권)',
    price: '1인 30,000원대~ (매장 확인 필요)',
    signature: '루프탑 한식 기반 양식',
    desc: '송정 해변 내려다보는 루프탑 레스토랑, 호텔 출신 셰프.',
    icon: 'view',
    link: 'https://map.naver.com/p/search/홀리라운지 송정본점',
  },
];
